#开发配置-只是简单等配置了一下
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://rm-bp1t37vdwz904rj8npo.mysql.rds.aliyuncs.com:3306/office?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: fy@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zjw.oa.entity
  mapperLocations: classpath:mapper/*.xml
server:
  #端口号
  port: 8081
#logging:
#  level: debug

filePath: E:/oaFile/